### ISSUE TITLE
Sri Lanka Flag is incorrect

### ISSUE THREAD

**Issue by Shajeel-Afzal** [joielechong/iso-country-flags-svg-collection#1]
Thanks creating this nice collection, However i see that the Sri Lanka flag is incorrect and is needed to be updated.

**Comment by joielechong** [comment]
As I'm currently busy right now, I can't make a promise to correct it now. Could you send me a PR?. Thank you.

**Comment by joielechong** [comment]
I've corrected the flag. Sorry, it takes me a decade to fix this.. :(
