### ISSUE TITLE
EU / Europe flag missing

### ISSUE THREAD

**Issue by tooomm** [joielechong/iso-country-flags-svg-collection#2]
see: https://en.wikipedia.org/wiki/Flag_of_Europe

**Comment by justinclift** [comment]
Good point, any interest in following this up? :smile:

**Comment by tooomm** [comment]
Thank you @joielechong (https://github.com/joielechong/iso-country-flags-svg-collection/commit/02a35c93218c16a16f972297c2fe2b7535aa1873)
